name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run deploy script on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.MCSHIFTBOT_SERVER_HOST }}
          username: root
          key: ${{ secrets.MCSHIFTBOT_SERVER_KEY }}
          script: |
            /opt/mcshiftbot/infra/deploy/deploy.sh
